### PR TITLE
Flood fill fix, Save as Image fix, repository files

### PR DESCRIPTION
**Pull request by SirEmentaler**
- Fixed the flood fill tool.
- Enabled the "Save as Image" functionality.
- Fixed zoom issues caused by using "Save as Image".
- Extended .gitignore.
- Added a VS12 solution file.

### CODE REVIEW

**Comment by blurredd** [comment]
@Violet-CLM is this project still active?

**Comment by blurredd** [comment]
@Violet-CLM, will these commits ever be merged? I would like to know whether I can contribute here or if I should contribute to @SirEmentaler's fork instead.

**Comment by Violet-CLM** [comment]
@blurredd @SirEmentaler  I don't know if I remember how to compile this anymore, but I'll try to take a look at them sometime this week.

**Comment by blurredd** [comment]
SirEmentaler added a solution file, so compiling was straightforward even on VS2015 and with no prior experience with using C#.

**Pull request merged**
